apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: aasop
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: aasop
type: Opaque
stringData:
  REDIS_PASSWORD: "ChangeMeInProduction!"
  REDIS_URL: "redis://:ChangeMeInProduction!@redis:6379"
