apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: aasop
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: aasop
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
