apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: aasop
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: aasop
type: Opaque
stringData:
  admin-user: admin
  admin-password: ChangeMeInProduction!
