apiVersion: v1
kind: Service
metadata:
  name: realtime
  namespace: aasop
  labels:
    app.kubernetes.io/name: realtime
    app.kubernetes.io/component: websocket
    app.kubernetes.io/part-of: aasop
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: realtime
  ports:
    - port: 4300
      targetPort: 4300
      protocol: TCP
      name: websocket
