apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: aasop
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: aasop
type: Opaque
stringData:
  POSTGRES_PASSWORD: "ChangeMeInProduction!"
  DATABASE_URL: "postgresql://aasop:ChangeMeInProduction!@postgres:5432/aasop?schema=public"
